$("#demo01").animatedModal(
  {modalTarget:'animatedModal1'}
);
$("#demo02").animatedModal(
  {modalTarget:'animatedModal2'}
);
$("#demo03").animatedModal(
  {modalTarget:'animatedModal3'}
);
$("#demo04").animatedModal(
  {modalTarget:'animatedModal4'}
);
